default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: safehaven
  password:
  socket: <%= ENV['MYSQL_SOCK'] %>

development:
  <<: *default
  database: safehaven_development
  username: safehaven

test:
  <<: *default
  database: safehaven_test
  username: safehaven

staging:
  <<: *default
  database: safehaven_staging
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  host:     <%= ENV['DATABASE_URL'] %>
  database: 'safehavenDb'
  username: <%= ENV['DATABASE_U'] %>
  password: <%= ENV['DATABASE_P'] %>
